### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by GsGotCookies** [songoda/KitPreview#1]
Hello, I really like this plugin and would want to use it however when I use the sign permissions and add them to group manager it still says when I deop myself that I cant use those signs? are the perms wrong or are there other perms for this plugin?

**Comment by songoda** [comment]
Hey there friend ^-^ this is the first time ive ever used GitHub to answer an issue :3  
So anyway I'm not sure exactly whats the matter with the perms for the signs but what I would do is look a sign and do /kp set <kit> as stated in my wiki. This should work way better then the legacy signs anyway. As for your perms they seem to work on my end you could add me on skype (Songoda) and I can help you try and figure them out if you like ^-^
